### ISSUE TITLE
Insertion of parameters in constructor call is not supported

### ISSUE THREAD

**Issue by algomaster99** [SpoonLabs/diffmin#75]
We have configured the insertion of arguments for `CtInvocation` but apparently, arguments can be inserted into `CtConstructorCall` which, surprisingly, is not extended from `CtInvocation`. Instead, it is inherited from `CtAbstractInvocation`. So a better solution would be to type cast [`element.getParent()`](https://github.com/SpoonLabs/diffmin/blob/main/src/main/java/com/diffmin/patch/PatchGeneration.java#L134) to `CtAbstractInvocation`. Thanks to [this line](https://github.com/KTH/spork/commit/1f2661b#diff-f0217932ee3a64ef9c9092f6e13f79ef364f1bff2c9f2ce4de1ff716596fbe42R44) in [KTH/spork](https://github.com/KTH/spork/) for revealing this case.

However, as of now, I am unable to reproduce this case. The above-mentioned case results in `Insertion of VariableRead in ConstructorCall` but whatever I do to replicate it, results in `Update of ConstructorCall`.

**PREV**
```java
class Arguments {

    public static void add(int x, int y) {
        Addition add = new Addition(x, y);
    }
}

class Addition {
    Addition(int x, int y) {
        System.out.println("Sum 2 elements");
    }
}
```
**NEW**
```java
class Arguments {

    public static void add(int x, int y, int z) {
        Addition add = new Addition(x, y, z);
    }
}

class Addition {
    Addition(int x, int y, int z) {
        System.out.println("Sum 3 elements");
    }
}
```

There were 4 operations but the one we are concerned with is:
```
Update ConstructorCall at Arguments:4
	new Addition(x, y) to new Addition(x, y, z)
```

**Comment by algomaster99** [comment]
Instead of creating the constructor definition like
```java
Addition(int x, int y, int z) {
    System.out.println("Sum 3 elements");
}
```
I used varargs.
```java
Addition(int... numbers) {
    System.out.println("Sum all numbers");
}
```

**Comment by slarse** [comment]
@algomaster99 Perhaps the reason why you get only "update constructor call" is that you're getting root operations, and the update is a root of the insertion. If I recall correctly, the label of a method invocation in gumtree-spoon is the signature of the method, and so that would warrant an update according to those semantics.

Try getting _all_ operations, and you should find an insertion in there. If that's the case, then this is again related to the fact that update operations can't really logically be root operations spoonlabs/gumtree-spoon-ast-diff#125. So we should turn to resolving that problem soonish.

**Comment by algomaster99** [comment]
> Try getting all operations, and you should find an insertion in there.

Yes, the insert operation was indeed there.

> So we should turn to resolving that problem soonish.

I will look into it and we can discuss in the next meeting.
